config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :libraries
  resources :counties
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/county.rb
class County < ApplicationRecord
    has_many :libraries , dependent: :destroy
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  before_action :set_county, only: %i[ show edit update destroy ]

  # GET /counties or /counties.json
  def index
    @counties = County.all
  end

  # GET /counties/1 or /counties/1.json
  def show
  end

  # GET /counties/new
  def new
    @county = County.new
  end

  # GET /counties/1/edit
  def edit
  end

  # POST /counties or /counties.json
  def create
    @county = County.new(county_params)

    respond_to do |format|
      if @county.save
        format.html { redirect_to county_url(@county), notice: "County was successfully created." }
        format.json { render :show, status: :created, location: @county }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @county.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counties/1 or /counties/1.json
  def update
    respond_to do |format|
      if @county.update(county_params)
        format.html { redirect_to county_url(@county), notice: "County was successfully updated." }
        format.json { render :show, status: :ok, location: @county }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @county.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counties/1 or /counties/1.json
  def destroy
    @county.destroy

    respond_to do |format|
      format.html { redirect_to counties_url, notice: "County was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_county
      @county = County.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def county_params
      params.require(:county).permit(:name, :population, :coordinates)
    end
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/views/counties/_county.html.erb
<div id="<%= dom_id county %>">
  <p>
    <strong>Name:</strong>
    <%= county.name %>
  </p>

  <p>
    <strong>Population:</strong>
    <%= county.population %>
  </p>

  <p>
    <strong>Coordinates:</strong>
    <%= county.coordinates %>
  </p>

</div>

app/views/counties/_form.html.erb
<%= form_with(model: county) do |form| %>
  <% if county.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(county.errors.count, "error") %> prohibited this county from being saved:</h2>

      <ul>
        <% county.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :population, style: "display: block" %>
    <%= form.number_field :population %>
  </div>

  <div>
    <%= form.label :coordinates, style: "display: block" %>
    <%= form.text_field :coordinates %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/counties/edit.html.erb
<h1>Editing county</h1>

<%= render "form", county: @county %>

<br>

<div>
  <%= link_to "Show this county", @county %> |
  <%= link_to "Back to counties", counties_path %>
</div>

app/views/counties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Counties</h1>

<div id="counties">
  <% @counties.each do |county| %>
    <%= render county %>
    <p>
      <%= link_to "Show this county", county %>
    </p>
  <% end %>
</div>

<%= link_to "New county", new_county_path %>

app/views/counties/new.html.erb
<h1>New county</h1>

<%= render "form", county: @county %>

<br>

<div>
  <%= link_to "Back to counties", counties_path %>
</div>

app/views/counties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @county %>


<!-- added @ sign to county here after consulting with chatgpt regarding error -->
<p>
 <strong>Libraries:</strong><br>
  <% @county.libraries.each do |library| %>
    <%= library.name %>
    <br>
  <% end %>
</p>
  

<div>
  <%= link_to "Edit this county", edit_county_path(@county) %> |
  <%= link_to "Back to counties", counties_path %>

  <%= button_to "Destroy this county", @county, method: :delete %>
</div>